% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  12pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=2.54cm]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={The Obama Administration's Significance on Public Low-Carbon Energy RD\&D Spending},
  pdfauthor={Irene Chang, Susanna Jenkins, and Jordan Mullens},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{The Obama Administration's Significance on Public Low-Carbon
Energy RD\&D Spending}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{\url{https://github.com/mullja21/Mullens_Chang_Jenkins_872_EDA_Final.git}}
\author{Irene Chang, Susanna Jenkins, and Jordan Mullens}
\date{}

\begin{document}
\maketitle

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

\hypertarget{rationale-and-research-questions}{%
\section{Rationale and Research
Questions}\label{rationale-and-research-questions}}

As the effects of climate change become more apparent, central and
federal governments have allocated more funding towards energy
technology research, development, and demonstration (RD\&D). The general
purpose of increased investment in low-carbon RD\&D is to move away from
high greenhouse gas emitting energy sources, such as fossil fuels, which
are a significant portion of anthropogenic emissions. Understanding how
energy technology RD\&D has evolved over time will be an informative
look into how the United States plans to address climate change through
the transition to low-carbon energy.

On the heels of the 2008 Financial Crisis, the newly inaugurated Obama
Administration signed into law the 2009 American Recovery and
Reinvestment Act (Recovery Act). While the main intent was to stimulate
the US economy, the Department of Energy (DOE) was allocated 4.5 billion
USD to modernize the electric power grid. Of that 4.5 billion USD, the
Recovery Act allowed the DOE to invest 600 million USD, along with 900
million USD industry cost share, in Smart Grid and Energy Storage
Demonstrations (2009 American Recovery and Reinvestment Act, n.d.).

For this analysis, low-carbon RD\&D spending in the US and Germany were
examined during two time periods: 1985-2008 and 2009-2015. Due to the
Recovery Act, we identified the Obama Administration (2009-2016) as a
pivotal moment in the US transition towards low-carbon energy; however,
the International Energy Agency dataset only provides US budget
information up to 2015. Germany was utilized as a control because it is
also a developed nation in the Western hemisphere. Therefore, we assume
Germany would act in an economically similar manner towards their energy
RD\&D pre-Obama Administration. The general trend of budgetary spending
for both the US and Germany, pre-2009, could be similar year on year. To
the best of our knowledge, Germany did not have any significant
energy-related policy spending around 2009, so there could be a
significant difference in low-carbon energy investment between the two
countries during the 2009-2015 time period. The objective of this
analysis is to gain valuable insight into how US investment into
low-carbon energy has shifted during the Obama Administration.

\textbf{Research Questions:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  In the United States, was the difference in means between Pre-Obama
  and Obama-era YoY percent change in public lower-carbon energy RD\&D
  spending significant?
\item
  Prior to Obama's presidency (1985-2008), was mean YoY percent change
  in public lower-carbon energy RD\&D spending in the United States
  significantly distinct from Germany?
\item
  During Obama's presidency (2009-2015), was mean YoY percent change in
  public lower-carbon energy RD\&D spending in the United States
  significantly distinct from Germany?
\end{enumerate}

\newpage

\hypertarget{dataset-information}{%
\section{Dataset Information}\label{dataset-information}}

The dataset utilized in this analysis was downloaded from the
International Energy Agency (IEA). The IEA's Energy Technology RD\&D
Budgets database provides spending information by energy technology in
IEA countries from 1974 to 2022. Data is collected from central or
federal government budgets and state-owned companies. Spending
categories (economic indicators) encompass renewables, nuclear power,
fossil fuels, hydrogen, fuel cells, energy efficiency, unallocated, and
total budget. There was public spending data on 32 countries and regions
with varying degrees of completeness for the 1974-2022 timeframe. The
budget data was available in various currencies, including Euros,
national currencies, and USD.

For this analysis, we wanted to consider low-carbon energy investments
in the US and Germany from 1985-2015. After downloading and importing
the dataset, columns were renamed, as the correct column names were
imported as the first row of the dataset. Next, the dataset was filtered
to only contain data for the United States and Germany from 1985-2015 in
USD (2021 prices and exchange rates).

In order to create a low carbon energy column, we further filtered the
data to include total budget, fossil fuels, and unallocated. We then had
to transpose the data as each year was its own column; however, we
wanted a single year column with the data for each of the economic
indicators to prepare the dataset for analysis. After filtering relevant
data, we created a separate low carbon energy (Low.Carbon.Energy)
column, which was total budget minus fossil fuel and unallocated. To
account for the difference in budgets relative to economic capability,
we normalized the budgets by creating another column for year-on-year
growth of the low carbon energy budgets. After all these steps were
taken, the data was considered ready for analysis.

\hypertarget{table-summarizing-the-dataset-information}{%
\subsection{Table summarizing the dataset
information}\label{table-summarizing-the-dataset-information}}

\begin{longtable}[]{@{}llll@{}}
\toprule()
Variable & Range\_Germany & Range\_US & Unit \\
\midrule()
\endhead
Total.Spending. & 1780.5 & 9094.0 & USD (millions) \\
Fossil.Fuel.Spending & 297.8 & 3919.8 & USD (millions) \\
Low.Carbon.Spending & 1586.6 & 5175.0 & USD (millions) \\
Year.over.Year.Change & 83.14 & 101.8. & \% change \\
\bottomrule()
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#create new data frame, change column names}
\NormalTok{RDD.newcolnames }\OtherTok{\textless{}{-}}\NormalTok{ RDD.raw }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{row\_to\_names}\NormalTok{(}\AttributeTok{row\_number =} \DecValTok{1}\NormalTok{)}

\CommentTok{\#The column names were imported improperly. The first row contains the correct }
\CommentTok{\#column names, so we used the janitor package since it has a function that }
\CommentTok{\#will replace the column names with the first row.}

\NormalTok{RDD.countries }\OtherTok{\textless{}{-}}
  \FunctionTok{filter}\NormalTok{(RDD.newcolnames,}
\NormalTok{         Country }\SpecialCharTok{==} \StringTok{"Germany"} \SpecialCharTok{|}\NormalTok{ Country }\SpecialCharTok{==} \StringTok{"United States"}\NormalTok{,}
\NormalTok{         Currency }\SpecialCharTok{==} \StringTok{"USD (2021 prices and exchange rates)"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}\StringTok{"Economic.Indicators"} \OtherTok{=} \StringTok{"Economic Indicators"}\NormalTok{)}

\NormalTok{RDD.final }\OtherTok{\textless{}{-}}\NormalTok{ RDD.countries }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Economic.Indicators }\SpecialCharTok{==} \StringTok{"Total Budget"} \SpecialCharTok{|}\NormalTok{ Economic.Indicators }\SpecialCharTok{==} \StringTok{"Unallocated "} \SpecialCharTok{|}\NormalTok{ Economic.Indicators }\SpecialCharTok{==} \StringTok{"Fossil fuels"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(}\StringTok{"Country"}\NormalTok{, }\StringTok{"Currency"}\NormalTok{, }\StringTok{"Economic.Indicators"}\NormalTok{, }\StringTok{"1985"}\NormalTok{, }\StringTok{"1986"}\NormalTok{, }\StringTok{"1987"}\NormalTok{, }\StringTok{"1988"}\NormalTok{, }\StringTok{"1989"}\NormalTok{, }\StringTok{"1990"}\NormalTok{, }\StringTok{"1991"}\NormalTok{, }\StringTok{"1992"}\NormalTok{, }\StringTok{"1993"}\NormalTok{, }\StringTok{"1994"}\NormalTok{, }\StringTok{"1995"}\NormalTok{, }\StringTok{"1996"}\NormalTok{, }\StringTok{"1997"}\NormalTok{, }\StringTok{"1998"}\NormalTok{, }\StringTok{"1999"}\NormalTok{, }\StringTok{"2000"}\NormalTok{, }\StringTok{"2001"}\NormalTok{, }\StringTok{"2002"}\NormalTok{, }\StringTok{"2003"}\NormalTok{, }\StringTok{"2004"}\NormalTok{, }\StringTok{"2005"}\NormalTok{, }\StringTok{"2006"}\NormalTok{, }\StringTok{"2007"}\NormalTok{, }\StringTok{"2008"}\NormalTok{, }\StringTok{"2009"}\NormalTok{, }\StringTok{"2010"}\NormalTok{, }\StringTok{"2011"}\NormalTok{, }\StringTok{"2012"}\NormalTok{, }\StringTok{"2013"}\NormalTok{, }\StringTok{"2014"}\NormalTok{, }\StringTok{"2015"}\NormalTok{)}

\NormalTok{RDD.transpose }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{t}\NormalTok{(RDD.final))}

\CommentTok{\#In our final data frame, we want each year to have its own row; however, }
\CommentTok{\#in the original dataset, each year was a column. We transposed it.}

\FunctionTok{colnames}\NormalTok{(RDD.transpose) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Germany.FossilFuels"}\NormalTok{, }\StringTok{"Germany.Unallocated"}\NormalTok{, }\StringTok{"Germany.TotalBudget"}\NormalTok{, }\StringTok{"US.FossilFuels"}\NormalTok{, }\StringTok{"US.Unallocated"}\NormalTok{, }\StringTok{"US.TotalBudget"}\NormalTok{)}

\NormalTok{RDD.transpose.rows }\OtherTok{\textless{}{-}}\NormalTok{ RDD.transpose[}\SpecialCharTok{!}\NormalTok{(}\FunctionTok{row.names}\NormalTok{(RDD.transpose) }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Country"}\NormalTok{, }\StringTok{"Currency"}\NormalTok{, }\StringTok{"Economic.Indicators"}\NormalTok{)),]}
 
\NormalTok{RDD.transpose.rows }\OtherTok{\textless{}{-}}\NormalTok{ RDD.transpose.rows }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate\_at}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{, as.numeric)}


\CommentTok{\#creating frame for US Data}
\NormalTok{RDD.US }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Year=}\FunctionTok{c}\NormalTok{(}\StringTok{"1985"}\NormalTok{, }\StringTok{"1986"}\NormalTok{, }\StringTok{"1987"}\NormalTok{, }\StringTok{"1988"}\NormalTok{, }\StringTok{"1989"}\NormalTok{, }\StringTok{"1990"}\NormalTok{, }\StringTok{"1991"}\NormalTok{, }\StringTok{"1992"}\NormalTok{, }\StringTok{"1993"}\NormalTok{, }\StringTok{"1994"}\NormalTok{, }\StringTok{"1995"}\NormalTok{, }\StringTok{"1996"}\NormalTok{, }\StringTok{"1997"}\NormalTok{, }\StringTok{"1998"}\NormalTok{, }\StringTok{"1999"}\NormalTok{, }\StringTok{"2000"}\NormalTok{, }\StringTok{"2001"}\NormalTok{, }\StringTok{"2002"}\NormalTok{, }\StringTok{"2003"}\NormalTok{, }\StringTok{"2004"}\NormalTok{, }\StringTok{"2005"}\NormalTok{, }\StringTok{"2006"}\NormalTok{, }\StringTok{"2007"}\NormalTok{, }\StringTok{"2008"}\NormalTok{, }\StringTok{"2009"}\NormalTok{, }\StringTok{"2010"}\NormalTok{, }\StringTok{"2011"}\NormalTok{, }\StringTok{"2012"}\NormalTok{, }\StringTok{"2013"}\NormalTok{, }\StringTok{"2014"}\NormalTok{, }\StringTok{"2015"}\NormalTok{), }
                     \AttributeTok{Fossil.Fuel=}\NormalTok{ RDD.transpose.rows}\SpecialCharTok{$}\NormalTok{US.FossilFuels,}
                     \AttributeTok{Unallocated=}\NormalTok{ RDD.transpose.rows}\SpecialCharTok{$}\NormalTok{US.Unallocated,}
                     \AttributeTok{Total.Budget=}\NormalTok{ RDD.transpose.rows}\SpecialCharTok{$}\NormalTok{US.TotalBudget) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Low.Carbon.Energy =} \FunctionTok{c}\NormalTok{(Total.Budget}\SpecialCharTok{{-}}\NormalTok{Fossil.Fuel}\SpecialCharTok{{-}}\NormalTok{Unallocated)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Percent.Change =}\NormalTok{ ((Low.Carbon.Energy }\SpecialCharTok{{-}}
                              \FunctionTok{lag}\NormalTok{(Low.Carbon.Energy))}\SpecialCharTok{/}\FunctionTok{lag}\NormalTok{(Low.Carbon.Energy))}\SpecialCharTok{*}\DecValTok{100}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Country =} \StringTok{"US"}\NormalTok{)}


\CommentTok{\#creating frame for Germany Data}
\NormalTok{RDD.Germany }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Year=}\FunctionTok{c}\NormalTok{(}\StringTok{"1985"}\NormalTok{, }\StringTok{"1986"}\NormalTok{, }\StringTok{"1987"}\NormalTok{, }\StringTok{"1988"}\NormalTok{, }\StringTok{"1989"}\NormalTok{, }\StringTok{"1990"}\NormalTok{, }\StringTok{"1991"}\NormalTok{, }\StringTok{"1992"}\NormalTok{, }\StringTok{"1993"}\NormalTok{, }\StringTok{"1994"}\NormalTok{, }\StringTok{"1995"}\NormalTok{, }\StringTok{"1996"}\NormalTok{, }\StringTok{"1997"}\NormalTok{, }\StringTok{"1998"}\NormalTok{, }\StringTok{"1999"}\NormalTok{, }\StringTok{"2000"}\NormalTok{, }\StringTok{"2001"}\NormalTok{, }\StringTok{"2002"}\NormalTok{, }\StringTok{"2003"}\NormalTok{, }\StringTok{"2004"}\NormalTok{, }\StringTok{"2005"}\NormalTok{, }\StringTok{"2006"}\NormalTok{, }\StringTok{"2007"}\NormalTok{, }\StringTok{"2008"}\NormalTok{, }\StringTok{"2009"}\NormalTok{, }\StringTok{"2010"}\NormalTok{, }\StringTok{"2011"}\NormalTok{, }\StringTok{"2012"}\NormalTok{, }\StringTok{"2013"}\NormalTok{, }\StringTok{"2014"}\NormalTok{, }\StringTok{"2015"}\NormalTok{),}
                          \AttributeTok{Fossil.Fuel=}\NormalTok{ RDD.transpose.rows}\SpecialCharTok{$}\NormalTok{Germany.FossilFuels,}
                          \AttributeTok{Unallocated=}\NormalTok{ RDD.transpose.rows}\SpecialCharTok{$}\NormalTok{Germany.Unallocated,}
                          \AttributeTok{Total.Budget=}\NormalTok{ RDD.transpose.rows}\SpecialCharTok{$}\NormalTok{Germany.TotalBudget) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Low.Carbon.Energy =}\NormalTok{ Total.Budget}\SpecialCharTok{{-}}\NormalTok{Fossil.Fuel}\SpecialCharTok{{-}}\NormalTok{Unallocated) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Percent.Change =}\NormalTok{ ((Low.Carbon.Energy }\SpecialCharTok{{-}}
                              \FunctionTok{lag}\NormalTok{(Low.Carbon.Energy))}\SpecialCharTok{/}\FunctionTok{lag}\NormalTok{(Low.Carbon.Energy))}\SpecialCharTok{*}\DecValTok{100}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Country =} \StringTok{"Germany"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Adding date column to US data frame and transforming it into date object. Also }
\CommentTok{\#adding a column to denote pre or Obama era for graphing.}
\NormalTok{RDD.US.Eras }\OtherTok{\textless{}{-}}\NormalTok{ RDD.US }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Date =} \FunctionTok{ymd}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(RDD.US}\SpecialCharTok{$}\NormalTok{Year, }\StringTok{"{-}01{-}01"}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Era =} \FunctionTok{ifelse}\NormalTok{(Year }\SpecialCharTok{\textless{}=} \DecValTok{2008}\NormalTok{, }\StringTok{"Pre"}\NormalTok{, }\StringTok{"Obama"}\NormalTok{))}

\CommentTok{\#creating one data frame for US and Germany data}
\NormalTok{US.and.Germany.RDD }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(RDD.Germany, RDD.US)}

\CommentTok{\#Adding Date column to US and Germany dataframe. Formatting so that column is }
\CommentTok{\#transformed to date class}

\NormalTok{US.and.Germany.RDD }\OtherTok{\textless{}{-}}\NormalTok{ US.and.Germany.RDD }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Date =} \FunctionTok{ymd}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(US.and.Germany.RDD}\SpecialCharTok{$}\NormalTok{Year, }\StringTok{"{-}01{-}01"}\NormalTok{))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Era =} \FunctionTok{ifelse}\NormalTok{(Year }\SpecialCharTok{\textless{}=} \DecValTok{2008}\NormalTok{, }\StringTok{"Pre"}\NormalTok{, }\StringTok{"Obama"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#file for Us and Germany}
\FunctionTok{write.csv}\NormalTok{(US.and.Germany.RDD, }\AttributeTok{row.names =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{file =} \StringTok{"./Processed\_Data/US.and.Germany.RDD.csv"}\NormalTok{)}

\CommentTok{\#File for US alone with eras}
\FunctionTok{write.csv}\NormalTok{(RDD.US.Eras, }\AttributeTok{row.names =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{file =} \StringTok{"./Processed\_Data/US.Eras.RDD.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\newpage

\hypertarget{exploratory-analysis}{%
\section{Exploratory Analysis}\label{exploratory-analysis}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#US Data Set}
\FunctionTok{dim}\NormalTok{(RDD.US.Eras)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 31  9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colnames}\NormalTok{(RDD.US.Eras)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Year"              "Fossil.Fuel"       "Unallocated"      
## [4] "Total.Budget"      "Low.Carbon.Energy" "Percent.Change"   
## [7] "Country"           "Date"              "Era"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(RDD.US.Eras)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#US and Germany}
\FunctionTok{dim}\NormalTok{(US.and.Germany.RDD)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 62  9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colnames}\NormalTok{(US.and.Germany.RDD)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Year"              "Fossil.Fuel"       "Unallocated"      
## [4] "Total.Budget"      "Low.Carbon.Energy" "Percent.Change"   
## [7] "Country"           "Date"              "Era"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(US.and.Germany.RDD)}
\end{Highlighting}
\end{Shaded}

The data was reviewed holistically to understand general trends between
1985 and 2015 for both the United States and Germany. Summary statistics
by country for each energy type and total budget are listed in the
tables below:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#creating Germany Data summary}
\NormalTok{Germ.summary }\OtherTok{\textless{}{-}}\NormalTok{ US.and.Germany.RDD }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Country}\SpecialCharTok{==} \StringTok{"Germany"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(Fossil.Fuel, Low.Carbon.Energy, Total.Budget, Percent.Change) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}

\CommentTok{\#kable(Germ.summary, caption = "Summary Statistics for Germany")}

\CommentTok{\#creating US Pre Obama summary}
\NormalTok{US.Pre.summary }\OtherTok{\textless{}{-}}\NormalTok{ US.and.Germany.RDD }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Country}\SpecialCharTok{==} \StringTok{"US"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Era}\SpecialCharTok{==} \StringTok{"Pre"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(Fossil.Fuel, Low.Carbon.Energy, Total.Budget, Percent.Change) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}

\CommentTok{\#kable(US.Pre.summary, caption = "Summary Statistics for US pre{-}Obama administration")}

\CommentTok{\#creating Obama admin summary}
\NormalTok{US.Obama.summary }\OtherTok{\textless{}{-}}\NormalTok{ US.and.Germany.RDD }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Country}\SpecialCharTok{==} \StringTok{"US"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Era}\SpecialCharTok{==} \StringTok{"Obama"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(Fossil.Fuel, Low.Carbon.Energy, Total.Budget, Percent.Change) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summary}\NormalTok{()}

\CommentTok{\#kable(US.Obama.summary, caption = "Summary Statistics for Obama administration")}
\end{Highlighting}
\end{Shaded}

First, the US and Germany total budgets, fossil fuel budgets, and low
carbon energy budgets were graphed. A line graph was utilized to
identify any potential trends in spending while a bar graph was utilized
to examine the relative magnitude of spending by country. Generally, the
United States spends more on RD\&D than Germany Figure
\textbackslash{}@ref(fig:Germany and US Line Plot for total budget).
Germany's spending appears to be less variable than US RD\&D spending as
demonstrated by Figure Figure @ref(fig:Germany and US Bar Plot for total
budget).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Germ and US Line Plot}
\NormalTok{US.Germ.total.plot }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(US.and.Germany.RDD,}
                              \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date,}
                                  \AttributeTok{y =}\NormalTok{ Total.Budget, }
                                  \AttributeTok{color =}\NormalTok{ Country)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{size=} \FloatTok{0.9}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{12500}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"tomato3"}\NormalTok{, }\StringTok{"darkblue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Total RDD Spending 1985{-}2015"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Amount in USD (2021 }\SpecialCharTok{\textbackslash{}n}\StringTok{ Prices and Exchange Rates)"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{,}
       \AttributeTok{color=} \StringTok{"Legend Title"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## i Please use `linewidth` instead.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(US.Germ.total.plot)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/Germany and US Line Plot for total budget-1.pdf}
\caption{US and Germany Total RDD Spending 1985 to 2015. Line graph used
to visualize potential trends.}
\end{figure}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create the US and Germ Total bar plot}
\NormalTok{US.Germ.total.Bar.plot }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(US.and.Germany.RDD, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y=}\NormalTok{ Total.Budget, }\AttributeTok{fill=}\NormalTok{ Country)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat=} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat=} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"tomato3"}\NormalTok{, }\StringTok{"darkblue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{15000}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{fill =} \StringTok{"Country"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{, }\AttributeTok{size =} \DecValTok{9}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Total RDD Spending"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Amount in USD (2021 }\SpecialCharTok{\textbackslash{}n}\StringTok{ Prices and Exchange Rates)"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(US.Germ.total.Bar.plot)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/Germany and US Bar Plot for total budget-1.pdf}
\caption{US and Germany Total RDD Spending 1985 to 2015. Bar graph used
to visually compare relative magnitude of total spending.}
\end{figure}

For both countries, it appears that Low Carbon RD\&D spending decreased
from 1985 to 2000 and increased from 2000 to 2015 @ref(fig: US and
Germany Low Carbon Spending 1985 to 2015. Line graph used to visualize
potential trends.)

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Low Carbon Germ and US Line Plot}
\NormalTok{US.Germ.lowC.plot }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(US.and.Germany.RDD,}
                              \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date,}
                                  \AttributeTok{y =}\NormalTok{ Low.Carbon.Energy, }
                                  \AttributeTok{color =}\NormalTok{ Country)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{size=} \FloatTok{0.9}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{12500}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"tomato3"}\NormalTok{, }\StringTok{"darkblue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Low Carbon RDD Spending 1985{-}2015"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Amount in USD (2021 }\SpecialCharTok{\textbackslash{}n}\StringTok{ Prices and Exchange Rates)"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{,}
       \AttributeTok{color=} \StringTok{"Legend Title"}\NormalTok{)}

\FunctionTok{print}\NormalTok{(US.Germ.lowC.plot)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/Low Carbon Germ and US Line Plot-1.pdf}
\caption{US and Germany Low Carbon Spending 1985 to 2015. Line graph
used to visualize potential trends.}
\end{figure}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create the US and Germ Low Carbon bar plot}
\NormalTok{US.Germ.low.carbon.Bar.plot }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(US.and.Germany.RDD, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y=}\NormalTok{ Low.Carbon.Energy, }\AttributeTok{fill=}\NormalTok{ Country)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat=} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat=} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"tomato3"}\NormalTok{, }\StringTok{"darkblue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{11000}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{fill =} \StringTok{"Country"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{, }\AttributeTok{size =} \DecValTok{9}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Low Carbon RDD Spending 1985{-}2015"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Amount in USD (2021 }\SpecialCharTok{\textbackslash{}n}\StringTok{ Prices and Exchange Rates)"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(US.Germ.low.carbon.Bar.plot)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/US and Germ Low Carbon-1.pdf}
\caption{US and Germany Low Carbon RDD Spending 1985 to 2015, Bar graph
used to visually compare relative magnitude of total spending.}
\end{figure}

It is unclear whether these changes are significant and further analysis
is needed. A few notable abnormalities in the Germany data set include
the years 1996, 1997, and 1998 where fossil fuel spending was well below
the average Figure .

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Fossil Fuel Germ and US Line Plot}
\NormalTok{US.Germ.fossil.plot }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(US.and.Germany.RDD,}
                              \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date,}
                                  \AttributeTok{y =}\NormalTok{ Fossil.Fuel, }
                                  \AttributeTok{color =}\NormalTok{ Country)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{size=} \FloatTok{0.9}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{12500}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"tomato3"}\NormalTok{, }\StringTok{"darkblue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Fossil Fuel RDD Spending 1985{-}2015"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Amount in USD (2021 }\SpecialCharTok{\textbackslash{}n}\StringTok{ Prices and Exchange Rates)"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{,}
       \AttributeTok{color=} \StringTok{"Legend Title"}\NormalTok{)}

\FunctionTok{print}\NormalTok{(US.Germ.fossil.plot)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/Fossil Fuel Germ and US Line-1.pdf}
\caption{US and Germany Fossil Fuel RDD Spending 1985 to 2015. Line
graph used to visualize potential trends.}
\end{figure}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create the US and Germ fossil fuel bar plot}
\NormalTok{US.Germ.Fossil.fuel.Bar.plot }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(US.and.Germany.RDD, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y=}\NormalTok{ Fossil.Fuel, }\AttributeTok{fill=}\NormalTok{ Country)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat=} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat=} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position =} \StringTok{"stack"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"tomato3"}\NormalTok{, }\StringTok{"darkblue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{5000}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{fill =} \StringTok{"Country"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{, }\AttributeTok{size =} \DecValTok{9}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Fossil Fuel of RDD Spending"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Amount in USD (2021 }\SpecialCharTok{\textbackslash{}n}\StringTok{ Prices and Exchange Rates)"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(US.Germ.Fossil.fuel.Bar.plot)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/US and Germ fossil fuel Bar-1.pdf}
\caption{US and Germany Fossil Fuel RDD Spending 1985 to 2015. Bar graph
used to visually compare relative magnitude of total spending.}
\end{figure}

Then, the US data was graphed alone to examine the different spending
categories, Fossil Fuels and Low Carbon Energy, against the total
spending Figure . In 2009, there is a noticeable increase in the total
spending for both fossil fuels and low carbon energy; the total budget
doubled from the previous year. After the initial increase in 2009, the
total budget, and consequently the low carbon energy and fossil fuel,
numbers appear to decline.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#US Line Plot}
\NormalTok{RDD.US.Eras.Line.plot }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(RDD.US.Eras, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ Total.Budget, }\AttributeTok{color=} \StringTok{"Total.Spending"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ Fossil.Fuel, }\AttributeTok{color=} \StringTok{"Fossil.Fuels"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ Low.Carbon.Energy, }\AttributeTok{color=} \StringTok{"Low.Carbon"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{, }\AttributeTok{size =} \DecValTok{9}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{name =} \StringTok{"Proportion of }\SpecialCharTok{\textbackslash{}n}\StringTok{ RDD Spending"}\NormalTok{, }\AttributeTok{values=} \FunctionTok{c}\NormalTok{(}
    \StringTok{"Fossil.Fuels"} \OtherTok{=} \StringTok{"midnightblue"}\NormalTok{, }
    \StringTok{"Low.Carbon"} \OtherTok{=} \StringTok{"darkolivegreen3"}\NormalTok{, }
    \StringTok{"Total.Spending"} \OtherTok{=} \StringTok{"sienna3"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_date}\NormalTok{(}\AttributeTok{date\_breaks =} \StringTok{"3 years"}\NormalTok{, }\AttributeTok{date\_labels =} \StringTok{"\%Y"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Proportion of }\SpecialCharTok{\textbackslash{}n}\StringTok{ United States RDD }\SpecialCharTok{\textbackslash{}n}\StringTok{ Spending 1985{-}2015"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Amount in USD (2021 }\SpecialCharTok{\textbackslash{}n}\StringTok{ Prices and Exchange Rates)"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{,}
       \AttributeTok{color=} \StringTok{"Legend Title"}\NormalTok{)}

\FunctionTok{print}\NormalTok{(RDD.US.Eras.Line.plot)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/Line Plot of All US RDD-1.pdf}
\caption{US RDD Spending 1985 to 2015}
\end{figure}

Based on these findings, we decided two-tailed t-tests should be
administered to determine whether any changes in RD\&D during the Obama
administration were significant. It was necessary to compare the US
pre-Obama administration and the Obama administration time periods with
the RD\&D spending for Germany. However, creating a standard metric was
required to conduct this analysis. Thus, the year over year change in
RD\&D for each energy type was calculated to draw comparisons.

\newpage

\hypertarget{analysis}{%
\section{Analysis}\label{analysis}}

The analysis of the RD\&D Budget data focuses on comparing the mean
year-over-year (YoY) percent change in public low-carbon energy RD\&D
spending in the period preceding Obama's presidency (1985-2008) to the
YoY percent change during Obama's presidency (2009-2015). To ensure any
Obama-era changes in public low-carbon RD\&D investment within the
United States are unique to the administration \& its domestic energy
policy agenda, and not co-occurring with global shifts in public RD\&D
investment, trend significance in the United States was compared to the
control, Germany. To analyze these trends statistically, rather than
visually, a series of two-sample t-tests was employed using the
RDD.US.Eras data frame and filtered US.and.Germany.RDD data frame to
separately address the three research questions.

\hypertarget{united-states-pre-obama-vs.-obama-era-analysis}{%
\subsection{United States Pre-Obama vs.~Obama-era
Analysis}\label{united-states-pre-obama-vs.-obama-era-analysis}}

\textbf{Question 1:} In the United States, was the difference in means
between Pre-Obama and Obama-era year-over-year percent change in public
lower-carbon energy RD\&D spending significant?

In the first two-sample t-test, we addressed the first research question
by looking at public low-carbon energy RD\&D spending in the United
States using RDD.US.Eras data frame to determine if the mean YoY percent
change prior to Obama's presidency (1985-2008) was as significant as the
mean YoY percent change during the Obama administration (2009-2015).
RDD.US.Eras Percent.Change was the continuous dependent variable, and
RDD.US.Eras Era was the categorical variable with two levels (Pre-Obama
and Obama-era).

\begin{itemize}
\item
  \textbf{Null Hypothesis 1 (H0):} Mean YoY change in public low-carbon
  RD\&D spending during the Obama presidency (2009-2015) was not
  statistically distinct from the Pre-Obama era (1985-2008) YoY change
  in spending
\item
  \textbf{Alternative Hypothesis 1 (H1):} Mean YoY change in public
  spending on lower-carbon energy RD\&D was significantly different
  during Obama's presidency.
\end{itemize}

The test returned a p-value of 0.5771 which is above our threshold of
significance (p \textless{} 0.05). Therefore, we fail to reject our null
hypothesis (H) that mean YoY change in public low-carbon RD\&D spending
during the Obama presidency (2009-2015) was not statistically distinct
from the Pre-Obama era (1985-2008) YoY change in spending.

Figure displays the year over year percent change in low carbon energy
RD\&D for both the pre-Obama and Obama time periods. A linear regression
was constructed and added to the YoY lines to examine the data trends
over time.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#plotting the pre{-}Obama data}
\NormalTok{RDD.US.Eras.plot }\OtherTok{\textless{}{-}}\NormalTok{ RDD.US.Eras }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}
         \FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{ Date,}
             \AttributeTok{y=}\NormalTok{ Percent.Change,}
             \AttributeTok{color=}\NormalTok{ Era)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{data =} \FunctionTok{subset}\NormalTok{(RDD.US.Eras, Era }\SpecialCharTok{==} \StringTok{"Pre"}\NormalTok{), }\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color=} \StringTok{"darkolivegreen4"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{data =} \FunctionTok{subset}\NormalTok{(RDD.US.Eras, Era }\SpecialCharTok{==} \StringTok{"Obama"}\NormalTok{), }\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color=} \StringTok{"dodgerblue3"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Year{-}over{-}Year Percent Change in Public }\SpecialCharTok{\textbackslash{}n}\StringTok{ Low{-}Carbon Energy RD\&D }\SpecialCharTok{\textbackslash{}n}\StringTok{ Spending: U.S."}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"YoY Percent Change"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"darkblue"}\NormalTok{, }\StringTok{"darkgreen"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{scale\_x\_date}\NormalTok{(}\AttributeTok{date\_breaks =} \StringTok{"2 years"}\NormalTok{, }\AttributeTok{date\_labels =} \StringTok{"\%Y"}\NormalTok{) }\SpecialCharTok{+}
\NormalTok{  our\_theme }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{))}
  
\FunctionTok{print}\NormalTok{(RDD.US.Eras.plot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1 rows containing non-finite values (`stat_smooth()`).
\end{verbatim}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1 row containing missing values (`geom_line()`).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1 rows containing missing values (`geom_point()`).
\end{verbatim}

\begin{figure}
\centering
\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/visualizing the US data-1.pdf}
\caption{US Year over Year RDD Spending 1985 to 2015}
\end{figure}

\hypertarget{pre-obama-united-states-vs.-germany-analysis}{%
\subsection{Pre-Obama United States vs.~Germany
Analysis}\label{pre-obama-united-states-vs.-germany-analysis}}

\textbf{Question 2:} Prior to Obama's presidency (1985-2008), was mean
year-over-year percent change in public lower-carbon energy RD\&D
spending in the United States significantly distinct from Germany?

To address the second question regarding pre-Obama spending in U.S. and
Germany, we needed to wrangle the data to only include records prior to
Obama's inauguration, for years 1985-2008. We then ran a two-sample
T-test on the filtered pre-Obama data to determine whether mean YoY
percent change in public RD\&D spending was statistically different
between the two counties. Pre.2009.US.Germany.RDD Percent.Change was the
continuous dependent variable, and Pre.2009.US.Germany.RDD Country was
the categorical variable with two levels (United States and Germany).

\begin{itemize}
\item
  \textbf{Null Hypothesis 2 (H0):} Prior to Obama's presidency, there
  was a significant difference in means between the U.S. and Germany for
  YoY percent change in public spending on lower-carbon energy RD\&D
\item
  \textbf{Alternative Hypothesis 2 (H1):} The difference in means
  between the U.S. and Germany for YoY percent change in public spending
  on lower-carbon energy RD\&D was not significant prior to Obama's
  presidency
\end{itemize}

Our test returned a p-value of 0.5113 which is above the threshold of
significance (p \textless{} 0.05). Therefore, we fail to reject the null
hypothesis (H0) that in the period prior to Obama's presidency
(1985-2008), mean year-over-year change in public low-carbon RD\&D
spending in the United States was statistically distinct from Germany.

Figure displays the year over year percent change in low carbon energy
RDD for the US and Germany during the pre-Obama administration time
period. A linear regression was constructed and added to the YoY lines
to examine the data trends over time.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#plotting the data}
\NormalTok{US.Germany.RDD.pre.plot }\OtherTok{\textless{}{-}}\NormalTok{ US.and.Germany.RDD }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Era }\SpecialCharTok{==} \StringTok{"Pre"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date,}
             \AttributeTok{y =}\NormalTok{ Percent.Change, }
             \AttributeTok{color =}\NormalTok{ Country)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{data =} \FunctionTok{subset}\NormalTok{(US.and.Germany.RDD, Country }\SpecialCharTok{==} \StringTok{"Germany"} \SpecialCharTok{\&}\NormalTok{ Era }\SpecialCharTok{==} \StringTok{"Pre"}\NormalTok{), }\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color=} \StringTok{"tomato2"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{data =} \FunctionTok{subset}\NormalTok{(RDD.US.Eras, Country }\SpecialCharTok{==} \StringTok{"US"} \SpecialCharTok{\&}\NormalTok{ Era }\SpecialCharTok{==} \StringTok{"Pre"}\NormalTok{), }\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color=} \StringTok{"blue3"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"tomato3"}\NormalTok{, }\StringTok{"darkblue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"YoY Change in Public Low{-}Carbon }\SpecialCharTok{\textbackslash{}n}\StringTok{ Energy RD\&D Spending: }\SpecialCharTok{\textbackslash{}n}\StringTok{ US vs. Germany"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Year{-}over{-}Year Percent Change"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{scale\_x\_date}\NormalTok{(}\AttributeTok{date\_breaks =} \StringTok{"1 years"}\NormalTok{, }\AttributeTok{date\_labels =} \StringTok{"\%Y"}\NormalTok{) }\SpecialCharTok{+}
\NormalTok{  our\_theme }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{, }\AttributeTok{size=}\DecValTok{9}\NormalTok{))}
  
\FunctionTok{print}\NormalTok{(US.Germany.RDD.pre.plot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1 rows containing non-finite values (`stat_smooth()`).
\end{verbatim}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1 rows containing non-finite values (`stat_smooth()`).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 2 rows containing missing values (`geom_line()`).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 2 rows containing missing values (`geom_point()`).
\end{verbatim}

\begin{figure}
\centering
\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/visualizing the pre US and Germany data together-1.pdf}
\caption{US and Germany Year over Year RDD Spending 1985 to 2008}
\end{figure}

\hypertarget{obama-era-united-states-vs.-germany-analysis}{%
\subsection{Obama-era United States vs.~Germany
Analysis}\label{obama-era-united-states-vs.-germany-analysis}}

\textbf{Question 3:} During Obama's presidency (2009-2015), was mean
year-over-year percent change in public lower-carbon energy RD\&D
spending in the United States significantly distinct from Germany?

We then conducted a similar two-sided t-test to address the third
question regarding Obama-era spending in the U.S. and Germany. After
wrangling the data to only include records during Obama's two-term
presidency, for years 2009-2015, we ran the analysis on the filtered
data to determine whether mean YoY percent change in Obama-era public
RD\&D spending was statistically different between the two counties.
Post.2009.US.Germany.RDD Percent.Change was the continuous dependent
variable, and Post.2009.US.Germany.RDD Country was the categorical
variable with two levels (United States and Germany).

\begin{itemize}
\item
  \textbf{Null Hypothesis 3 (H0):} During Obama's presidency, mean YoY
  percent change in public spending on lower-carbon energy RD\&D in the
  United States was not statistically distinct from Germany YoY change
  in spending
\item
  \textbf{Alternative Hypothesis 3 (H1):} Obama-era YoY percent change
  in public lower-carbon energy RD\&D spending in the United States was
  significantly different from Germany YoY change in spending
\end{itemize}

The final two-sided t-test returned a p-value of 0.857 which is above
the threshold of significance (p \textless{} 0.05). Therefore, we fail
to reject the null hypothesis (H0) that mean YoY change in public
low-carbon RD\&D spending in the U.S. was not statistically distinct
from Germany during the Obama Administration.

figure displays the year over year percent change in low carbon energy
RDD for the US and Germany during the Obama administration time period.
A linear regression was constructed and added to the YoY lines to
examine the data trends over time.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#plotting the data}
\NormalTok{US.Germany.RDD.Obama.plot }\OtherTok{\textless{}{-}}\NormalTok{ US.and.Germany.RDD }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Era }\SpecialCharTok{==} \StringTok{"Obama"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date,}
             \AttributeTok{y =}\NormalTok{ Percent.Change, }
             \AttributeTok{color =}\NormalTok{ Country)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{data =} \FunctionTok{subset}\NormalTok{(US.and.Germany.RDD, Country }\SpecialCharTok{==} \StringTok{"Germany"} \SpecialCharTok{\&}\NormalTok{ Era }\SpecialCharTok{==} \StringTok{"Obama"}\NormalTok{), }\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color=} \StringTok{"tomato2"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{data =} \FunctionTok{subset}\NormalTok{(RDD.US.Eras, Country }\SpecialCharTok{==} \StringTok{"US"} \SpecialCharTok{\&}\NormalTok{ Era }\SpecialCharTok{==} \StringTok{"Obama"}\NormalTok{), }\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color=} \StringTok{"blue3"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"tomato3"}\NormalTok{, }\StringTok{"darkblue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"YoY Change in Public Low{-}Carbon }\SpecialCharTok{\textbackslash{}n}\StringTok{ Energy RD\&D Spending: }\SpecialCharTok{\textbackslash{}n}\StringTok{ US vs. Germany"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Year{-}over{-}Year Percent Change"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{scale\_x\_date}\NormalTok{(}\AttributeTok{date\_breaks =} \StringTok{"1 years"}\NormalTok{, }\AttributeTok{date\_labels =} \StringTok{"\%Y"}\NormalTok{) }\SpecialCharTok{+}
\NormalTok{  our\_theme }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{, }\AttributeTok{size=}\DecValTok{9}\NormalTok{))}
  
\FunctionTok{print}\NormalTok{(US.Germany.RDD.Obama.plot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{figure}
\centering
\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/visualizing Obama US and Germany data together-1.pdf}
\caption{US and Germany Year over Year RDD Spending 2009 to 2015}
\end{figure}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#United States Pre{-}Obama vs Obama{-}era analysis}

\NormalTok{US.Pre.v.Post.Obama.ttest }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(RDD.US.Eras}\SpecialCharTok{$}\NormalTok{Percent.Change }\SpecialCharTok{\textasciitilde{}} 
\NormalTok{                                      RDD.US.Eras}\SpecialCharTok{$}\NormalTok{Era)}

\NormalTok{US.Pre.v.Post.Obama.ttest}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  RDD.US.Eras$Percent.Change by RDD.US.Eras$Era
## t = 0.58747, df = 6.3612, p-value = 0.5771
## alternative hypothesis: true difference in means between group Obama and group Pre is not equal to 0
## 95 percent confidence interval:
##  -23.01113  37.81629
## sample estimates:
## mean in group Obama   mean in group Pre 
##           8.1695963           0.7670191
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Pre{-}Obama US vs Germany analysis}

\NormalTok{Pre.}\FloatTok{2009.}\NormalTok{US.Germany.RDD }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(US.and.Germany.RDD, Year }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{1985}\SpecialCharTok{:}\DecValTok{2008}\NormalTok{))}
  
\NormalTok{Pre.}\FloatTok{2009.}\NormalTok{US.Germany.ttest }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(Pre.}\FloatTok{2009.}\NormalTok{US.Germany.RDD}\SpecialCharTok{$}\NormalTok{Percent.Change }\SpecialCharTok{\textasciitilde{}} 
\NormalTok{                                      Pre.}\FloatTok{2009.}\NormalTok{US.Germany.RDD}\SpecialCharTok{$}\NormalTok{Country)}

\NormalTok{Pre.}\FloatTok{2009.}\NormalTok{US.Germany.ttest}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  Pre.2009.US.Germany.RDD$Percent.Change by Pre.2009.US.Germany.RDD$Country
## t = -0.66411, df = 32.7, p-value = 0.5113
## alternative hypothesis: true difference in means between group Germany and group US is not equal to 0
## 95 percent confidence interval:
##  -12.743123   6.472836
## sample estimates:
## mean in group Germany      mean in group US 
##            -2.3681247             0.7670191
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Obama{-}era US vs Germany analysis}

\NormalTok{Post.}\FloatTok{2009.}\NormalTok{US.Germany.RDD }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(US.and.Germany.RDD, Year }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{2009}\SpecialCharTok{:}\DecValTok{2015}\NormalTok{))}
  
\NormalTok{Post.}\FloatTok{2009.}\NormalTok{US.Germany.ttest }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(Post.}\FloatTok{2009.}\NormalTok{US.Germany.RDD}\SpecialCharTok{$}\NormalTok{Percent.Change }\SpecialCharTok{\textasciitilde{}} 
\NormalTok{                                      Post.}\FloatTok{2009.}\NormalTok{US.Germany.RDD}\SpecialCharTok{$}\NormalTok{Country)}

\NormalTok{Post.}\FloatTok{2009.}\NormalTok{US.Germany.ttest}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  Post.2009.US.Germany.RDD$Percent.Change by Post.2009.US.Germany.RDD$Country
## t = -0.18605, df = 8.0331, p-value = 0.857
## alternative hypothesis: true difference in means between group Germany and group US is not equal to 0
## 95 percent confidence interval:
##  -33.51499  28.50738
## sample estimates:
## mean in group Germany      mean in group US 
##              5.665790              8.169596
\end{verbatim}

\newpage

\hypertarget{summary-and-conclusions}{%
\section{Summary and Conclusions}\label{summary-and-conclusions}}

\textbf{List of p-values from two-sided t-test analyses.}

\begin{longtable}[]{@{}ll@{}}
\toprule()
Analysis & p\_value \\
\midrule()
\endhead
US.PreObama.v.ObamaEra & 0.5771 \\
PreObama.US.v.Germany & 0.5113 \\
ObamaEra.US.v.Germany & 0.857 \\
\bottomrule()
\end{longtable}

The results from the two-sided t-tests, which indicated non-significant
differences in mean YoY percent change in public low-carbon energy RD\&D
spending between different time periods and between the United States
and Germany, were unexpected and contrary to the initial hypotheses. The
initial exploration of relationships using the raw budget data for both
the United States and Germany suggested a significant distinction in
U.S. lower-carbon energy RD\&D spending at the onset of Obama's two-term
presidency.

Regarding findings from the analysis of the first research question, the
insignificant difference in mean YoY percent change in public
lower-carbon energy RD\&D spending between the pre-Obama and Obama-era
periods does not necessarily suggest that a substantial shift in funding
priorities or levels of investment did not occur during Obama's
presidency. The unexpected result (p-value = 0.5771), and failure to
reject the null hypothesis, might be explained by the selection of the
continuous dependent variable, mean year-over-year percent change in
public lower-carbon energy RD\&D spending. After visualizing
relationships in the raw data -- particularly the substantial low-carbon
energy RDD budgetary swings starting in Obama's first year in office --
statistical analysis focused on the average YoY percent change in
spending. While this approach captures the overall direction \&
magnitude of change in RD\&D spending, it smooths out short-term
fluctuations over the selected time period and presents a less
pronounced view of the trends. Thus, the analysis of the mean YoY
percent change offset the potentially significant fluctuations that were
initially explored rather than emphasizing specific annual variations in
Obama's first years in office. Regardless, the low-carbon energy policy
wins, particularly within Obama's first term, that underlay the original
rationale affirm that it was a pivotal moment in the United States'
transition towards renewable energy.

Similarly, regarding the second and third research questions, the
non-significant difference in mean YoY percent change in public
lower-carbon energy RD\&D spending between the U.S. and Germany during
both the pre-Obama (p-value of 0.5113) and Obama-era (p-value = 0.857)
time periods contradicts the initial expectations. Failing to reject the
null hypotheses, these findings indicate that the two countries had
similar public investment trends in clean energy technologies,
suggesting that factors other than the Obama Administration's policy
interventions may have influenced changes in low-carbon RD\&D spending.
Again, despite the divergent trends observed in the analysis, landmark
policy such as the 2009 American Recovery and Reinvestment Act helps
validate the original rationale and hypotheses that the Obama
Administration marked a notable shift in sustainable energy funding
priorities and investment levels.

The unexpected findings from these analyses underscores the importance
of further exploration to understand the underlying factors driving
RD\&D spending in the United States and Germany. To gain a more
comprehensive understanding of the significance of low-carbon RD\&D
spending during Obama's two-term presidency, it would be beneficial to
uncouple financial spending from environmental impact. While there was
not a significant increase in low carbon energy investments during the
Obama administration, this does not mean that there was not a
significant change in environmental impact, such as a potential decrease
in greenhouse gas emissions resulting from increased spending through
the 2009 Recovery Act. Therefore, further literature review and research
on the environmental impact stemming from increased funding through the
Department of Energy may be beneficial to understanding the full
magnitude the Obama Administration had on the transition towards lower
carbon energy through RD\&D investment.

\newpage

\#Scripts, data and code The repository linked at the beginning contains
both the raw data, wrangled data, and code utilized. They are found in
their respective folders.

\#Quality assurance Please note that any conclusions created by this
report are limited as only one source of data and one variable were
utilized. Further examination of additional metrics and countries are
recommended for future analyses.

\newpage

\#Appendix

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create the combined bar plot}
\NormalTok{RDD.US.Eras.Bar.plot }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(RDD.US.Eras, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ Total.Budget, }\AttributeTok{fill =} \StringTok{"Total.budget"}\NormalTok{), }\AttributeTok{stat=} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position =} \StringTok{"identity"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ Low.Carbon.Energy, }\AttributeTok{fill =} \StringTok{"Low.Carbon"}\NormalTok{), }\AttributeTok{stat=} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position =} \StringTok{"identity"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ Fossil.Fuel, }\AttributeTok{fill =} \StringTok{"Fossil.Fuels"}\NormalTok{), }\AttributeTok{stat=} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position =} \StringTok{"identity"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Fossil.Fuels"} \OtherTok{=} \StringTok{"midnightblue"}\NormalTok{, }\StringTok{"Low.Carbon"} \OtherTok{=} \StringTok{"darkolivegreen3"}\NormalTok{, }\StringTok{"Total.budget"} \OtherTok{=} \StringTok{"sienna3"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{fill =} \StringTok{"Budget Portion"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Proportion of RDD Spending"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Amount in USD (2021 }\SpecialCharTok{\textbackslash{}n}\StringTok{ Pricess and Exchange Rates)"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(RDD.US.Eras.Bar.plot)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/Combined bar plot of US RDD-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#plotting US and Germany data}
\NormalTok{US.Germany.RDD.plot }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(US.and.Germany.RDD,}
                              \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Date,}
                                  \AttributeTok{y =}\NormalTok{ Percent.Change, }
                                  \AttributeTok{color =}\NormalTok{ Country)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{data =} \FunctionTok{subset}\NormalTok{(US.and.Germany.RDD, Country }\SpecialCharTok{==} \StringTok{"Germany"}\NormalTok{), }\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color=} \StringTok{"tomato2"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{data =} \FunctionTok{subset}\NormalTok{(RDD.US.Eras, Country }\SpecialCharTok{==} \StringTok{"US"}\NormalTok{), }\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{color=} \StringTok{"dodgerblue3"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"tomato3"}\NormalTok{, }\StringTok{"darkblue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"YoY Change in Public Low{-}Carbon }\SpecialCharTok{\textbackslash{}n}\StringTok{ Energy RD\&D Spending: }\SpecialCharTok{\textbackslash{}n}\StringTok{ US vs. Germany"}\NormalTok{,}
       \AttributeTok{y=}\StringTok{"Year{-}over{-}Year Percent Change"}\NormalTok{,}
       \AttributeTok{x=}\StringTok{"Year"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{scale\_x\_date}\NormalTok{(}\AttributeTok{date\_breaks =} \StringTok{"2 years"}\NormalTok{, }\AttributeTok{date\_labels =} \StringTok{"\%Y"}\NormalTok{) }\SpecialCharTok{+}
\NormalTok{  our\_theme }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{))}
  
\FunctionTok{print}\NormalTok{(US.Germany.RDD.plot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1 rows containing non-finite values (`stat_smooth()`).
\end{verbatim}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1 rows containing non-finite values (`stat_smooth()`).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 2 rows containing missing values (`geom_line()`).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 2 rows containing missing values (`geom_point()`).
\end{verbatim}

\begin{figure}
\centering
\includegraphics{Chang_Jenkins_Mullens_ENV872_Final_files/figure-latex/visualizing the US and Germany data together-1.pdf}
\caption{US and Germany Year over Year RDD Spending 1985 to 2015}
\end{figure}

\hypertarget{references}{%
\section{References}\label{references}}

Office of Electricity. (n.d.). 2009 American Recovery and Reinvestment
Act. U.S. Department of Energy. Retrieved May 2, 2023, from
\url{https://www.energy.gov/oe/2009-american-recovery-and-reinvestment-act}.

\textless add references here if relevant, otherwise delete this
section\textgreater{}

\end{document}
